### ISSUE TITLE
Can not use this with post in back-end

### ISSUE THREAD

**Issue by thientran1707** [Gisonrg/IVLE-Login#1]
Hi,

Somehow your method works well in Postman. But when I do similarly with a POST request from back-end then it returns me the HTML file to login?

**Comment by Gisonrg** [comment]
Hi,

So sorry it doesn't work. This is mainly because of the CORS setting of the IVLE server. By default, Postman have the permission for cross domain request but a normal backend may not, that's why it can work on postman but may not work on your backend.
As this method is only for experiment purpose, I suggest you may have to fall back to the IVLE login page for production. 😢
